### ISSUE TITLE
Image not displaying 

### ISSUE THREAD

**Issue by Walkerbo** [ilimei/vscode-plugin-blp-preview#1]
The image does not load, I just have the spinning wheel.

I have watched the wheel for more than 15 min.

**Comment by ilimei** [comment]
could you give me the special image file?

**Comment by Walkerbo** [comment]
[SwarmIcon.zip](https://github.com/ilimei/vscode-plugin-blp-preview/files/8158558/SwarmIcon.zip)

**Comment by ilimei** [comment]
the blp file is blp2
will support in future

**Comment by Walkerbo** [comment]
Ok, thanks for that.

**Comment by ilimei** [comment]
already publish 0.1.5
