### ISSUE TITLE
更新到0.1.5后很多模型不动了

### ISSUE THREAD

**Issue by PhoenixZeng** [ilimei/vscode-plugin-blp-preview#2]
0.1.4是正常的

**Comment by PhoenixZeng** [comment]
我试了好几个模型没一个能动的

**Comment by ilimei** [comment]
应该是引入bug了 我晚上修复一下

**Comment by PhoenixZeng** [comment]
另外我注意到你好像即使贴图所在路径和模型不在正确的相对路径上 也可以正常加载 你应该是有搜索工作区的操作吧
建议可以先走模型内部的贴图路径 如果没有再搜索工作区 这样也许可以提升加载速度

**Comment by ilimei** [comment]
是一个小bug引起的，搜索war3的内部模型的时候导致搜索了整个mpq文件
