### ISSUE TITLE
转换blp后生成的文件在哪呢?

### ISSUE THREAD

**Issue by PhoenixZeng** [ilimei/vscode-plugin-blp-preview#5]
不过这个功能想不到转换格式的应用场景.. 主要还是各类转换工具已经多如牛毛了.还是批量的

**Comment by PhoenixZeng** [comment]
噢 做wow插件的可能可以用上吧

**Comment by PhoenixZeng** [comment]
目前感觉可能比较有意义的插件功能:

轻量化的模型修改
  如:便捷的修改模型的贴图路径
调整blp尺寸/压缩blp质量/调整为二次幂
等

**Comment by ilimei** [comment]
第一个问题：主要是blp转png是我需要的功能，现在做图存储的源文件都是png，打包的时候增量转blp，有些资源是网上找的只有blp，想ps处理只能先转换一下

关于模型修改，也有个现成的技术，我晚上更新上去（mdl和mdx相互转化），我目前都是直接修改mdl文件，mdl是纯文本，跟png类似，也是打包的时候自动转换成mdx文件，mdl文件好处是一些简单的模型，例如单个贴图旋转 缩放 透明 多贴图的动画都阔以直接编辑，不需要3d模型编辑工具。

**Comment by ilimei** [comment]
调整blp尺寸/压缩blp质量/调整为二次幂
等 
关于这个我阔以提供一个node-canvas扩展，我目前也在用，阔以脚本直接绘图 两张贴图合并等（自动暗图标，自动边框，图片尺寸自动缩放到最近的二次幂）

**Comment by PhoenixZeng** [comment]
> 第一个问题：主要是blp转png是我需要的功能，现在做图存储的源文件都是png，打包的时候增量转blp，有些资源是网上找的只有blp，想ps处理只能先转换一下

我是看到左侧资源栏png/jpg的右键菜单上加了个转换至blp 虽然我没应用场景 但是点击了没反应 不知道输出到哪了 所以反馈了一下

> 关于这个我阔以提供一个node-canvas扩展，我目前也在用，阔以脚本直接绘图 两张贴图合并等

这个我也写了个类似的工具自己在使用 所以就是提个更新方向的建议 哈哈哈

**Comment by ilimei** [comment]
> 我是看到左侧资源栏png/jpg的右键菜单上加了个转换至blp 虽然我没应用场景 但是点击了没反应 不知道输出到哪了 所以反馈了一下

应该是报错了，帮忙打开控制台看看报什么错误，我修复一下
> 这个我也写了个类似的工具自己在使用 所以就是提个更新方向的建议 哈哈哈

哈哈哈 咱们阔以加个qq（514222057）交流下，有兴趣也阔以一起完善下这个插件
